FT- createParcelEndpoint
Hurntre/SendIT pull request #25
Opened 2020-04-02 21:13 UTC by Hurntre

- Created an endpoint that creates a parcel
- the controller also associates parcels and users
- i wrote tests
- I made the parcel routes RESTful

#### Description

#### Type of change

- [ ]
- [ ]

#### How Has This Been Tested?

- [ ] Unit testing

#### Checklist:

#### PT-ID

[](url)

#### Screenshots

#### Questions:

2021-02-16 23:02 UTC, vic3king commented on server/db/index.js
> +      process.env.NODE_ENV === 'development'
I dont think we need to do this. This db should be for tests alone.

2021-02-16 23:02 UTC, vic3king commented on package.json
> +    "decache": "^4.5.1",
What do we use this for?

2021-02-16 23:02 UTC, vic3king commented on server/app.js
> +app.use(express.urlencoded({ extended: true }));
What does this do?

2021-02-16 23:03 UTC, vic3king commented on server/controllers/parcel.js
> +/* eslint-disable require-jsdoc */
Please remove

2021-02-16 23:05 UTC, vic3king commented on server/db/schemas/parcelSchema.js
> +  status: { type: String, default: 'Pickup Requested' },
maybe set the status on default to be just `requested` other possible statuses to consider `delivered`, `picked` ,`in-transit`

2021-02-16 23:09 UTC, vic3king commented on server/db/schemas/parcelSchema.js
>    receiverAddress: { type: String, required: true },
A cool thing we could do is create a user account for the receiver and only reference the ID on this model.

We could then send the login details to the receiver to log in and track their deliveries.

We can discuss this later.

2021-02-16 23:10 UTC, vic3king commented on server/middlewares/addressValidation.js
> +    if (receiverAddress && receiverAddress.length > 4) {
use Joi validation to sanitize, your date.

2021-02-16 23:12 UTC, vic3king commented on server/middlewares/deliveryDateSetter.js
> +  // to be updated with code that factor pickup date and address put in by user
This would be nice.

2021-02-16 23:16 UTC, vic3king commented on server/middlewares/pickUpDateValidation.js
> +  if (timeDifference < 86400000) {
maybe `86400000` save this to variables that describe what it is

2021-02-16 23:17 UTC, vic3king commented on server/middlewares/pickUpDateValidation.js
> +      error: 'pickUpdate date has to be to a day from now at least',
```suggestion
      error: 'pickup date has to be at least a day from now.',
```

2021-02-16 23:21 UTC, vic3king commented on tests/integration/parcelEndpoints.test.js
> +    describe('address validation', () => {
This doesn't describe what the test block does. Shouldn't it be something like

`Should create a parcel`

2021-02-16 23:22 UTC, vic3king commented on server/middlewares/addressValidation.js
> +        error: 'Address not found, enter a valid address',
This shouldn't be here... We can only make this claim via google maps

2021-02-16 23:23 UTC, vic3king commented on tests/integration/parcelEndpoints.test.js
> +            expect(error).to.equal('Address not found, enter a valid address');
See above comment on middleware

2021-02-16 23:26 UTC, vic3king commented on tests/integration/parcelEndpoints.test.js
> +    describe('parcel validation', () => {
This shouldn't be a separate describe block. Could be part of an existing one .

2021-02-16 23:29 UTC, vic3king requested changes
Solid work here. Let's make it better. Some more general comments

- Don’t return all parcels on login(create an endpoint to get all parcels for a particular user... would be cool to make this request via the parcel model)
- Make sure unnecessary spaces are not accepted on the endpoint, or make sure you dont store values like `Name: "    name. "`(Joi easily handles this)
- use google maps to validate receivers and senders address in dev and prod
- Add unique fields middleware for maybe the delivery title and desc I was able to create duplicates with the same details
- No coverage drops

2021-02-17 06:56 UTC, Hurntre commented on package.json
> +    "decache": "^4.5.1",
I think it is a sub dependency. I didn't install that so it definitely got there through another package. I will try uninstalling it if I can't track it

2021-02-17 06:57 UTC, Hurntre commented on server/app.js
> +app.use(express.urlencoded({ extended: true }));
that is a form parser that comes with the updated version of express. it is a middleware that the app uses on all routes to read the data coming from forms. the "extended:true" allows the reading of nested form data

2021-02-17 07:06 UTC, Hurntre commented on server/controllers/parcel.js
> +/* eslint-disable require-jsdoc */
Done

2021-02-17 07:08 UTC, Hurntre commented on server/db/index.js
> +      process.env.NODE_ENV === 'development'
Noted and change reverted

2021-02-17 07:13 UTC, Hurntre commented on package.json
> +    "decache": "^4.5.1",
removed

2021-02-17 07:19 UTC, Hurntre commented on server/controllers/parcel.js
> +/* eslint-disable require-jsdoc */
You did put it in the auth controller file though. I put it here too to avoid the eslint error when running the test or trying to start the server.

this has to do with the documentation style you used for the controller files

2021-02-17 07:21 UTC, Hurntre commented on server/middlewares/deliveryDateSetter.js
> +  // to be updated with code that factor pickup date and address put in by user
Yes, I will work on that in the future when I have solidified the structure of the app

2021-02-17 07:36 UTC, Hurntre commented on package.json
> +    "decache": "^4.5.1",
uninstall with no side effect.

2021-02-17 22:40 UTC, vic3king commented on server/controllers/parcel.js
> +/* eslint-disable require-jsdoc */
Yeah, I know. I'm saying remove it so, the docs error can be fixed.

2021-02-17 22:43 UTC, vic3king commented on server/db/schemas/parcelSchema.js
> +  status: { type: String, default: 'Requested' },
```suggestion
  status: { type: String, default: 'requested' },
```

2021-02-17 22:46 UTC, vic3king commented on server/middlewares/newParcelValidation.js
> +    expectedDeliveryDate: Joi.date(),
```suggestion
    expectedDeliveryDate: Joi.date().required(),
```

2021-02-17 22:55 UTC, vic3king commented on server/middlewares/pickUpDateValidation.js
> +const verifyPickUpDate = (req, res, next) => {
Were you able to manually test this? You should write some unit tests for this function.
https://stackoverflow.com/questions/3224834/get-difference-between-2-dates-in-javascript Have a look at this, dealing with dates is a tricky part of JS.

2021-02-17 22:56 UTC, vic3king commented on server/routes/index.js
> +router.use('/parcels', parcelRoute);
deep.

2021-02-17 22:57 UTC, vic3king commented on tests/integration/parcelEndpoints.test.js
> +              'expectedDeliveryDate'
can we add assertions that test for the returned values?

2021-02-17 22:58 UTC, vic3king commented on tests/integration/parcelEndpoints.test.js
> +            'pickup date has to be at least a day from now'
Nice

2021-02-17 23:03 UTC, vic3king commented on server/db/seeders/seed.js
> +      pickUpDate: Date.now() + 1,
Is there a reason for having these?

Date.now() + 86500000,
Date.now() + 1

2021-02-17 23:06 UTC, vic3king requested changes
Dropped a few more comments. Let me know when I can have a look again. Welldone

2021-02-19 10:32 UTC, Hurntre commented on server/middlewares/pickUpDateValidation.js
> +const verifyPickUpDate = (req, res, next) => {
Thanks. I will look at it and work on that Unit test

2021-02-19 10:33 UTC, Hurntre commented on server/db/seeders/seed.js
> +      pickUpDate: Date.now() + 1,
I really don't understand how Date works so I am just doing it randomly. I will have to research the date module and learn more about it.

2021-02-19 10:35 UTC, Hurntre commented on tests/integration/parcelEndpoints.test.js
> +              'expectedDeliveryDate'
That would be nice. I will work on that

2021-02-20 17:57 UTC, vic3king commented on server/db/seeders/seed.js
> +      pickUpDate: Date.now() + 1,
got you, for now, I'll suggest you stay consistent with one working pattern.

2021-02-23 20:14 UTC, vic3king requested changes
Left a few tiny comments, also look through there seems to be some comments that have not been addressed. Welldone

2021-02-23 20:14 UTC, vic3king commented on server/config/emailService.js
> +      // eslint-disable-next-line no-console
Please disable this from the eslint file so we can remove these comments

2021-02-23 20:14 UTC, vic3king commented on tests/integration/parcelEndpoints.test.js
> +    it('should fetch all parcels in parcel collection after login', done => {
```suggestion
    it('should fetch all parcels in parcel collection', done => {
```

2021-03-02 16:09 UTC, vic3king commented on .eslintrc
> +        "off",
🤔

2021-03-02 16:11 UTC, vic3king requested changes

2021-03-02 16:11 UTC, vic3king commented on server/middlewares/pickUpDateValidation.js
> +  if (typeof pickUpDate === 'string') {
We actually don't need this since we're already making use of Joi validation.

2021-03-02 16:11 UTC, vic3king commented on server/middlewares/pickUpDateValidation.js
> +  return res.status(400).json({
Was this added because if the eslint return error?

2021-03-03 10:20 UTC, Hurntre commented on server/middlewares/pickUpDateValidation.js
> +  return res.status(400).json({
The app is parsing the data entered into ISO format that doesnt have methods. I guess I have handled that so the if statement isnt actually needed.

2021-03-03 10:24 UTC, Hurntre commented on .eslintrc
> +        "off",
I dont know what the jsdoc error, thus i am lost about how to solve it. any pointers will help. I know it would be nice to understand it

2021-03-17 02:54 UTC, merged